name: "Title Check"

on:
  pull_request_target:
    types:
      - opened
      - edited

concurrency:
  group: title-check-${{ github.event.pull_request.number }}
  cancel-in-progress: true

permissions:
  contents: read
  pull-requests: write

jobs:
  title-check:
    runs-on: ubuntu-latest
    steps:
      - uses: thehanimo/pr-title-checker@7fbfe05602bdd86f926d3fb3bccb6f3aed43bc70 # v1.4.3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          pass_on_octokit_error: false
          github_configuration_owner: ${{ github.repository_owner }}
          github_configuration_repo: ${{ github.event.repository.name }}
          github_configuration_path: .github/pr-title-checker-config.json
          github_configuration_ref: ${{ github.event.pull_request.base.ref }}
